### ISSUE TITLE
Use well named variables for opcode arguments before use

### ISSUE THREAD

**Issue by mitch-fuel** [FuelLabs/fuel-vm#220] opened 2022-09-20 21:36 UTC
Reading the implementations of the opcodes often required referencing the spec to determine what each of the variables are as they use the a, b, c... argument order naming convention. These parameters have specific meanings and should immediately be placed into variables that return those meanings to the variables.

**Comment by xgreenx** [comment] 2023-05-12 11:56
Duplicate of the https://github.com/FuelLabs/fuel-vm/issues/349

**Closed by xgreenx** 2023-05-12 11:56 UTC
Labels: documentation, fuel-vm
